### ISSUE TITLE
Problemas con sonar Clous y la Calidad del código

### ISSUE THREAD

**Issue by JoelFEscobar** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct09-filesystem-notes-app-alu0101130408#2]
Buenas tardes @esegredo.
Estoy implementando la práctica y a la hora de pushear el código al repositorio de github las actiosn se ejecutan correctamente y no dan fallos pero sonar cloud pone que no ha pasado la prueba de calidad de código. Sin embargo, leyendo dentro de la propia web de sonar Cloud pone que no debería usar la función "Math.random" la cual uso para generar de forma aleatoria un id para un usuario een el sistema. Por lo que no se  bien que debería hacer para solucionar la calidad del codigo.

Un saludo y gracias de antemano.

**Comment by esegredo** [comment]
Hola Joel,

En este caso, tienes que adoptar una medida manual, tal y como te propone Sonar Cloud, para utilizar un generador de números aleatorios más seguro como Crypto. Debido a esa regla concreta, la puerta de calidad no se va a cumplir nunca si no eliminas Math.random de tu código. No obstante, esto se trata de un ejemplo académico y no se tendrá en cuenta negativamente el hecho de que no pases la puerta de calidad.

En cualquier caso, tienes otras opciones diferentes para asignar ID o nombres de usuario. No es necesario generar números aleatorios para esta tarea.

Saludos.
